version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5001:5001"  # Keep port 5001 exposed for local development
    volumes:
      - user_uploads:/app/user_uploads
      - app_data:/app/data
    env_file:
      - .env  # Load environment variables
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge  # Use a bridge network for isolation

volumes:
  user_uploads:
  app_data:
