version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5001:5001"  # Expose port 5001 for your Flask app
    volumes:
      - ./user_uploads:/app/user_uploads  # Local directory for user uploads
      - ./data:/app/data  # Local directory for app data
    env_file:
      - .env  # Load environment variables securely from the .env file
    depends_on:
      - redis  # Ensure Redis starts before Flask app
    networks:
      - app_network  # Use a private network for service communication

  redis:
    image: redis:alpine  # Use Redis in an alpine container for efficiency
    command: ["redis-server", "--save", "900", "1", "--appendonly", "no"]  # Disable persistence
    networks:
      - app_network  # Keep Redis isolated on the app_network

networks:
  app_network:
    driver: bridge  # Using the default bridge network for isolation