version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./user_uploads:/app/user_uploads  # Maps your local user_uploads to container
      - ./data:/app/data  # Maps a writable local data folder to /app/data inside the container
    environment:
      - FLASK_ENV=production  # Add environment variables here if needed