version: '3.9'
services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app:ro  # Optional, use ':ro' to make it read-only in production
    environment:
      - FLASK_ENV=production  # Add environment variables here if needed