name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only read access to the repository
      packages: write  # Allow pushing Docker images
