name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your main branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t djurg/data-mirroring:latest .

      - name: Push the Docker image
        run: docker push djurg/data-mirroring:latest
